### ISSUE TITLE
Yell Ability & Fling Ability

### ISSUE THREAD

**Issue by Unfellowed** [Psykotikism/Mutant_Tanks#113]
Can you help me adjust the config? I need them to appear at the same time.
My config:
>
 		"Spawn"
		{
			"Spawn Type"			"4"
		}
		"Combo"
		{
			"Combo Duration"		"5,0"
			"Combo Interval"		"5,0"
			"Combo Range"			"500,500"
			"Combo Range Chance"		"0,100"
			"Combo Range Cooldown"		"0,5"
			"Combo Set"			"Yell,Fling"
			"Combo Type Chance"		"100,0,0,0,0,0"
		}
		"Fling Ability"
		{
			"Combo Ability"			"1"
			"Ability Enabled"		"1"
			"Fling Force"			"300"
			// "Fling Range"		"500"
			// "Fling Range Chance"		"100"
			// "Fling Range Cooldown"	"5"
		}
		"Yell Ability"
		{
			"Combo Ability"			"1"			
			"Ability Enabled"		"1"
			"Yell Damage"			"5"
			// "Yell Duration"		"5"
			// "Yell Interval"		"5"
			"Yell Mode"			"0"
			"Yell Pitch"			"100"
			// "Yell Range"			"500"
		}

**Comment by Psykotikism** [comment]
try this:
```cpp
"Spawn"
{
	"Spawn Type"			"4"
}
"Combo"
{
	"Combo Duration"		"5.0,0.0"
	"Combo Interval"		"6.0,0.0"
	"Combo Range"			"500.0,500.0"
	"Combo Range Chance"		"0.0,100.0"
	"Combo Range Cooldown"		"0,5"
	"Combo Set"			"Yell,Fling"
	"Combo Type Chance"		"100.0,100.0"
}
"Fling Ability"
{
	"Combo Ability"			"1"
	"Ability Enabled"		"1"
	"Fling Force"			"300"
}
"Yell Ability"
{
	"Combo Ability"			"1"
	"Ability Enabled"		"1"
	"Yell Damage"			"5"
	"Yell Mode"			"0"
	"Yell Pitch"			"100"
}
```

**Comment by Unfellowed** [comment]
Yell Ability doesn't seem to work. 🙁
https://youtu.be/FKURNE2L3Ro

**Comment by Psykotikism** [comment]
try this:
```cpp
"Spawn"
{
	"Spawn Type"				"4"
}
"Combo"
{
	"Combo Chance"				"50.0,50.0"
	"Combo Damage"				"5.0,0.0"
	"Combo Delay"				"0.0,1.0"
	"Combo Duration"			"1.0,0.0"
	"Combo Interval"			"1.0,0.0"
	"Combo Range"				"500.0,500.0"
	"Combo Range Chance"			"50.0,50.0"
	"Combo Range Cooldown"			"1,1"
	"Combo Set"				"Yell,Fling"
	"Combo Type Chance"			"100.0,0.0,0.0,0.0,0.0,0.0"
}
"Fling Ability"
{
	"Combo Ability"				"1"
	"Ability Enabled"			"1"
	"Fling Force"				"300"
}
"Yell Ability"
{
	"Combo Ability"				"1"
	"Ability Enabled"			"1"
	"Yell Mode"				"0"
	"Yell Pitch"				"100"
}
```

**Comment by Unfellowed** [comment]
Perfect config, I thought "Combo Chance" is only used when Tank punches or throws rocks at survivors. Thank you sir!
