### ISSUE TITLE
Mutant SI

### ISSUE THREAD

**Issue by Unfellowed** [Psykotikism/Mutant_Tanks#116]
Can you add a configuration to disable the skill as soon as SI appears? (I just want to make Boomer look like Leaker :D)

https://github.com/Psykotikism/Mutant_Tanks/assets/115072518/7e256a9b-bae5-455d-ae77-6468a0d0ed41

**Comment by Psykotikism** [comment]
Are you talking about the fire when the SI appears?

Try to set `Fire Death` to `0`.

**Comment by Unfellowed** [comment]
Yep, it was absurd for them to stand in the fire without losing blood and Survivors easily know where they appear.
