### ISSUE TITLE
error logged when starting server

### ISSUE THREAD

**Issue by eduaris123** [Psykotikism/Mutant_Tanks#120]
Hi, I am currently using mt for my versus server but when I start the server this error appears in the log, there is spam of that error in my log also from others from the same mt.  

"L 03/31/2024 - 23:25:03: [SM] Exception reported: Invalid Handle c8900a3a (error 2). It looks like you've chosen the wrong hook callback signature for your setup and you're trying to access the wrong handle.
 Blaming: mutant_tanks\mutant_tanks.smx
Call stack trace:
  [0] DHookParam.IsNull
 [1] Line 24427, WeaponHandling::mreReplaceTankPost"

"[mutant_tanks\mutant_tanks.smx] [MT] Failed to detour: MTDetour_CTerrorPlayer::OnLadderMount"

"L 03/31/2024 - 11:33:47: [SM] Exception reported: Invalid Handle cbc02228 (error 2). It looks like you've chosen the wrong hook callback signature for your setup and you're trying to access the wrong handle.
Blaming: mutant_tanks\mutant_tanks.smx
Call stack trace:
[0] DHookParam.IsNull
[1] Line 24427, WeaponHandling::mreReplaceTankPost
 [3] SDKCall
[4] Line 2456, l4dd\l4dd_natives.sp::Native_ZombieManager_ReplaceTank
[6] L4D_ReplaceTank
[7] Line 644, C:\Program Files (x86)\Steam\steamapps\common\Left 4 Dead 2\left4dead2\addons\sourcemod\scripting\l4d_tank_pass.sp::TankPass
L 03/31/2024 - 11:33:47: [SM]   [8] Line 387, C:\Program Files (x86)\Steam\steamapps\common\Left 4 Dead 2\left4dead2\addons\sourcemod\scripting\l4d_tank_pass.sp::OfferMenuHandler
L 03/31/2024 - 11:45:32: Error log file session closed."

"L 03/31/2024 - 23:25:03: [SM] Exception reported: Invalid Handle c8900a3a (error 2). It looks like you've chosen the wrong hook callback signature for your setup and you're trying to access the wrong handle.
[SM] Blaming: mutant_tanks\mutant_tanks.smx
 [SM] Call stack trace:
 [SM]   [0] DHookParam.IsNull
[SM]   [1] Line 24427, WeaponHandling::mreReplaceTankPost"

I am using the latest version of mutant tank.,,

**Comment by Psykotikism** [comment]
> "[mutant_tanks\mutant_tanks.smx] [MT] Failed to detour: MTDetour_CTerrorPlayer::OnLadderMount"

This will be fixed in the next update.

> "L 03/31/2024 - 11:33:47: [SM] Exception reported: Invalid Handle cbc02228 (error 2). It looks like you've chosen the wrong hook callback signature for your setup and you're trying to access the wrong handle.
> [SM] Blaming: mutant_tanks\mutant_tanks.smx
> [SM] Call stack trace:
> [SM] [0] DHookParam.IsNull
> [SM] [1] Line 24427, WeaponHandling::mreReplaceTankPost

I don't get this error on any version but I will look into it.

**Comment by MiCura-BR** [comment]
Hello Psy,
I've also been receiving this error for some time now, but I didn't want to
bother you, as the plugin is working fine. Only this error appears in the
log

L 07/21/2024 - 10:44:04: SourceMod error session started
L 07/21/2024 - 10:44:04: Info (map "c5m1_waterfront") (file
"d:\tcafiles\users\left4dead2\addons\sourcemod\logs\errors_20240721.log")
L 07/21/2024 - 10:44:04: [mutant_tanks\mutant_tanks.smx] [MT] Failed to
detour: MTDetour_CTerrorPlayer::OnLadderMount
L 07/21/2024 - 10:52:18: Error log file session closed.

Em dom., 21 de jul. de 2024 às 15:47, Psykotikism ***@***.***>
escreveu:

**Comment by Psykotikism** [comment]
> Hello Psy,
> I've also been receiving this error for some time now, but I didn't want to bother you, as the plugin is working fine. Only this error appears in the log

> L 07/21/2024 - 10:44:04: SourceMod error session started
> L 07/21/2024 - 10:44:04: Info (map "c5m1_waterfront") (file "d:\tcafiles\users\left4dead2\addons\sourcemod\logs\errors_20240721.log")
> L 07/21/2024 - 10:44:04: [mutant_tanks\mutant_tanks.smx] [MT] Failed to detour: MTDetour_CTerrorPlayer::OnLadderMount
> L 07/21/2024 - 10:52:18: Error log file session closed.

Okay I will fix it in the next update.
